# see https://www.appveyor.com/docs/build-configuration/
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

install:
# install giversion.
# gitversion will set some appveyor settings with version information
- choco install gitversion.portable -pre -y
- gitversion /l console /output buildserver

before_build:
# 

build_script:
- dotnet restore
- dotnet build

after_build:
#

before_test:
# install opencover and codecov for exporting the coverage results.
- choco install opencover.portable
- choco install codecov

test_script:
# - dotnet test src/Playground.Calculator.MsTest.Test/Playground.Calculator.MsTest.Test.csproj
# - dotnet test src/Playground.Calculator.xUnit.Test/Playground.Calculator.xUnit.Test.csproj
#
# todo: script to combine libraries and run dotnet test only once?
# todo:  -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*"
# -mergeoutput
# - OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test src/Playground.Calculator.xUnit.Test/Playground.Calculator.xUnit.Test.csproj" -oldstyle -filter:"+[Playground*]* -[Playground*.Test]*" -hideskipped:Filter -returntargetcode -output:".\coverage-dotnet-1.xml"
- OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test src/Playground.Calculator.MsTest.Test/Playground.Calculator.MsTest.Test.csproj" -oldstyle -filter:"+[Playground*]* -[Playground*.Test]*" -hideskipped:Filter -returntargetcode -output:".\coverage-dotnet-2.xml"

after_test:
# - codecov -f coverage-dotnet-1.xml
- codecov -f coverage-dotnet-2.xml
# - codecov -f coverage-dotnet1.xml

artifacts:
  # Dll to check if and how version information is added.
- path: src\Playground.Calculator\bin\Release\netstandard2.0\*.dll
  name: Library
  # Add the csproj to check if the version number is updated.
- path: src\Playground.Calculator\Playground.Calculator.csproj
  name: csproj
- path: coverage-dotnet*xml
  name: coverage
# - path: coverage-dotnet1.xml
#   name: coverag1