image: Visual Studio 2017

# see https://www.appveyor.com/docs/build-configuration/
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  sonar_login:
    secure: yODIZSU12799e3GeKvmUnUMSpzmnl3fTUI+vxW1BKI4RkKsTVFx9Qi0aFSNmuA3e
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y

# version: 1.0.{build}
# configuration: Release
# platform: Any CPU

#
# Patch .NET Core csproj files to set version information
#
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  # assembly_version: '{version}'
  # file_version: '{version}'
  # informational_version: '{version}'


# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
init:
# nothing here

install:
- choco install gitversion.portable -pre -y
- choco install "msbuild-sonarqube-runner" -y
- choco install opencover.portable
- choco install codecov
# Run gitversion before appveyor will patch the csproj files with version info.
# Note that the full patch is specified. Otherwise the default (older) gitversion will be used.
- C:\ProgramData\chocolatey\lib/gitversion.portable/tools/gitversion.exe /l console /output buildserver

before_build:
- dotnet restore
- .scripts\InitializeSonarqubeAnalysis.bat

build_script:
- msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# after_build:

# before_test:

test_script:
- .scripts\TestCoverage.bat

after_test:
- .scripts\RunSonarqubeAnalysis.bat
- codecov -f coverage-dotnet.xml

# build_success:

# on_finish:

artifacts:
  # Dll to check if and how version information is added.
- path: src\Playground.Calculator\bin\Release\netstandard2.0\*.dll
  name: Library
  # Add the csproj to check if the version number is updated.
- path: src\Playground.Calculator\Playground.Calculator.csproj
  name: csproj
- path: coverage-dotnet.xml
  name: coverage
# - path: coverage-dotnet1.xml
#   name: coverag1