# see https://www.appveyor.com/docs/build-configuration/
environment:
  # see https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  # sonarqube login token
  sonar_login:
    secure: yODIZSU12799e3GeKvmUnUMSpzmnl3fTUI+vxW1BKI4RkKsTVFx9Qi0aFSNmuA3e

version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

install:
# install giversion.
# gitversion will set some appveyor settings with version information
- choco install gitversion.portable -pre -y
- C:\ProgramData\chocolatey\lib/gitversion.portable/tools/gitversion.exe /l console /output buildserver
# - gitversion /l console /output buildserver

before_build:
- dotnet restore
- choco install "msbuild-sonarqube-runner" -y
# - SonarQube.Scanner.MSBuild.exe begin /k:"PlaygroundDotNetCoreDevelop" /d:"sonar.organization=coenm-github" /d:"sonar.host.url=https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage-dotnet.xml" /d:"sonar.login=%sonar_login%" /v:%appveyor_build_version%

build_script:
- dotnet build
# - dotnet msbuild

after_build:
#

before_test:
# install opencover and codecov for exporting the coverage results.
- choco install opencover.portable
- choco install codecov

test_script:
# - dotnet test src/Playground.Calculator.MsTest.Test/Playground.Calculator.MsTest.Test.csproj
# - dotnet test src/Playground.Calculator.xUnit.Test/Playground.Calculator.xUnit.Test.csproj
- C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test src/Playground.Calculator.xUnit.Test/Playground.Calculator.xUnit.Test.csproj" -oldstyle -filter:"+[Playground*]* -[Playground*.Test]*" -hideskipped:Filter -returntargetcode -mergeoutput -output:".\coverage-dotnet.xml"
- C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test src/Playground.Calculator.MsTest.Test/Playground.Calculator.MsTest.Test.csproj" -oldstyle -filter:"+[Playground*]* -[Playground*.Test]*" -hideskipped:Filter -returntargetcode -mergeoutput -output:".\coverage-dotnet.xml"

after_test:
- codecov -f coverage-dotnet.xml
- dotnet clean
# sonar.cpd.cross_project
# /d:sonar.projectBaseDir="src" /d:sonar.cs.opencover.reportsPaths="coverage-dotnet.xml"
- SonarQube.Scanner.MSBuild.exe begin /k:"PlaygroundDotNetCoreDevelop" /n:"Playground .netcore ci" /d:sonar.cs.opencover.reportsPaths="coverage-dotnet.xml" /d:"sonar.organization=coenm-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%sonar_login%" /v:%appveyor_build_version% /d:"sonar.branch=%GitVersion_BranchName%" /d:"sonar.cpd.cross_project=true"
- MSBuild.exe /t:Rebuild
- SonarQube.Scanner.MSBuild.exe end /d:sonar.login="%sonar_login%"

artifacts:
  # Dll to check if and how version information is added.
- path: src\Playground.Calculator\bin\Release\netstandard2.0\*.dll
  name: Library
  # Add the csproj to check if the version number is updated.
- path: src\Playground.Calculator\Playground.Calculator.csproj
  name: csproj
- path: coverage-dotnet.xml
  name: coverage
# - path: coverage-dotnet1.xml
#   name: coverag1